version: 0.2

env:
  variables:
    NODE_ENV: production
    
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      
  pre_build:
    commands:
      - echo Running tests...
      - npm test
      
  build:
    commands:
      - echo Building the application...
      - npm run build
      
  post_build:
    commands:
      - echo Build process completed
      
artifacts:
  files:
    - 'dist/**/*'
    - 'package.json'
  name: my-app-$(date +%Y-%m-%d)
  
cache:
  paths:
    - 'node_modules/**/*'
