version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
  build:
    commands:
      - echo Build phase started on `date`
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
